### ISSUE TITLE
iş bölgüsü

### ISSUE THREAD

**Issue by samraosmanova** [CodeAcademyLab/CMSproject#11]
- [x] Add, Update, Delete posts - Samra
- [ ] Add, Update, Delete users - @skerimov 
- [ ] Uploading files, display them in a table 3MB limit - @vidadim

**_DEADLINE 14/04/2016_**

**Comment by samraosmanova** [comment]
Veziyyet ne yerdedir?

**Comment by vidadim** [comment]
git hub conflict verdi onu düzəldənmədim... bilmirəm heç Laraveli türkçə qaynaq axtararkən 
Neden Laravel kullanmıyorum? ;-) gözəl məqalə rastlaşdım
http://aligundogdu.com/neden-laravel-kullanmiyorum/

**Comment by samraosmanova** [comment]
@vidadim  
kodlari mene gonder o zaman

**Comment by samraosmanova** [comment]
@skerimov muellim user teref hazirdir?
