### ISSUE TITLE
Front end üçün son düzəlişlər edilməlidir 

### ISSUE THREAD

**Issue by vidadim** [CodeAcademyLab/CMSproject#8]
Orxan Fərmanlı ilə baxdıq bu düzəlişlər olunmalıdır

1. Login page
2. Links  (tıqlananda açılsın deyə bağlantılar) 
3. Dropdown in sidebar (Publish -de category ve post üçün)

əslində bir çox düzəlişlər edilmiş olmalidir amma şənbədən bəri dəyişiklik olmayıbm kontrol edib push edərdiniz layihəyə zəhmət olmasa əksik qalan hissələri (pull request yolayardınız)

 @CodeAcademyLab/code16105

**Comment by samraosmanova** [comment]
Done
